// frontend/src/lib/components/BackupsDialog.svelte
<script lang="ts">
    // frontend/src/lib/components/BackupsDialog.svelte
import { listBackups } from '$lib/client/services/storage.svelte';
import type { BackupData } from '$lib/types';

let { open = $bindable(false) }: { open?: boolean } = $props();

let dialogEl = $state<HTMLDialogElement>();
let backups: BackupData[] = $state([]);
let loading = $state(false);
let error = $state('');

$effect(() => {
  if (open && dialogEl) {
    loadBackups();
    dialogEl.showModal();
  }
});

function onDialogClose() {
  open = false;
}

async function loadBackups() {
  loading = true;
  error = '';
  try {
    backups = await listBackups();
  } catch (e) {
    error = 'Failed to load backups';
  } finally {
    loading = false;
  }
}

async function downloadBackup(backup: BackupData) {
  const url = await backup.getDownloadURL();
  const a = document.createElement('a');
  a.href = url;
  a.download = backup.name;
  a.click();
}

function parseBackupDate(filename: string): Date {
  const name = filename.replace('.tar.gz', '');
  const [datePart, timePart] = name.split('_');
  if (!datePart || !timePart) return new Date(0);
  const [year, month, day] = datePart.split('-').map(Number);
  const [hour, minute] = timePart.split(':').map(Number);
  return new Date(year, month - 1, day, hour, minute);
}

const sortedBackups = $derived(
  [...backups]
    .map((b) => ({
      ...b,
      displayName: b.name.replace('.tar.gz', ''),
      date: parseBackupDate(b.name),
    }))
    .sort((a, b) => b.date.getTime() - a.date.getTime()),
);

function close() {
  open = false;
}
</script>

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<dialog bind:this={dialogEl} class="modal" onclose={onDialogClose}>
  <div class="modal-box">
    <div class="mb-4 flex items-center justify-between">
      <h3 class="text-lg font-bold">Backups</h3>
      <form method="dialog">
        <button class="btn btn-circle btn-ghost btn-sm">✕</button>
      </form>
    </div>

    {#if loading}
      <div class="flex justify-center py-8">
        <span class="loading loading-spinner loading-lg"></span>
      </div>
    {:else if error}
      <div class="alert alert-error">
        <span>{error}</span>
        <button onclick={loadBackups} class="btn btn-sm">Retry</button>
      </div>
    {:else if sortedBackups.length === 0}
      <p class="py-8 text-center text-base-content/60">No backups found</p>
    {:else}
      <div class="max-h-96 overflow-y-auto">
        {#each sortedBackups as backup}
          <button
            onclick={() => downloadBackup(backup)}
            class="btn btn-ghost w-full justify-between"
          >
            <span class="text-sm">📁 {backup.displayName}</span>
            <span class="text-xs text-base-content/60">⬇ Download</span>
          </button>
        {/each}
      </div>
    {/if}
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

// frontend/components/dialogs/BackupsDialog.vue
<template>
  <v-card>
    <v-card-title>
      <span class="headline">Backup List</span>
      <v-spacer></v-spacer>
      <v-btn icon @click="$emit('close')">
        <v-icon>mdi-close</v-icon>
      </v-btn>
    </v-card-title>
    <v-card-text>
      <v-list class="scrollable-list">
        <v-list-item
          v-for="(backup, index) in sortedBackups"
          :key="index"
          @click="downloadBackup(backup)"
        >
          <v-list-item-content>
            <v-list-item-title>{{ backup.name }}</v-list-item-title>
          </v-list-item-content>
          <v-list-item-action>
            <v-btn icon @click="downloadBackup(backup)">
              <v-icon>mdi-download</v-icon>
            </v-btn>
          </v-list-item-action>
        </v-list-item>
      </v-list>
    </v-card-text>
  </v-card>
</template>

<script lang="ts">
import Vue from 'vue';
import { BackupData } from '~/@types';

export default Vue.extend({
  name: 'VideoPlayer',
  data: () => ({
    backups: [] as BackupData[],
  }),
  computed: {
    sortedBackups(): BackupData[] {
      return this.backups
        .map((backup) => ({
          ...backup,
          name: backup.name.replace('.tar.gz', ''),
          date: this.parseBackupDate(backup.name.replace('.tar.gz', '')),
        }))
        .sort((a, b) => b.date.getTime() - a.date.getTime());
    },
  },
  async mounted() {
    const backups = await this.$accessor.storage.listBackups();
    console.log(backups);
    this.backups = backups;
  },
  methods: {
    parseBackupDate(name: string): Date {
      const [datePart, timePart] = name.split('_');
      const [year, month, day] = datePart.split('-').map(Number);
      const [hour, minute] = timePart.split(':').map(Number);
      return new Date(year, month - 1, day, hour, minute);
    },
    async downloadBackup(backup: BackupData) {
      try {
        const url = await backup.getDownloadURL();
        const link = document.createElement('a');
        link.href = url;
        link.download = backup.name;
        link.click();
      } catch (error) {
        console.error('Error downloading backup:', error);
      }
    },
  },
});
</script>

<style scoped>
.headline {
  font-weight: bold;
}
.scrollable-list {
  max-height: 400px;
  overflow-y: auto;
}
</style>
